rname: rename_tree exit 0 bug fixed

diff --git a/scripts/rname b/scripts/rname
--- a/scripts/rname
+++ b/scripts/rname
@@ -324,19 +324,19 @@ filter_paths >> "$temp_file"
 	if [ $manual_files -eq 0 ] && [ $manual_dirs -eq 0 ]; then
 		rename_dirs_auto
 		rename_files_auto
-		exit 0
+		return
 	fi
 	# manual renaming dirs
 	if [ $manual_dirs -eq 1 ] && [ $manual_files -eq 0 ]; then
 		rename_dirs_manual
 		rename_files_auto
-		exit 0
+		return
 	fi
 	# manual renaming files
 	if [ $manual_files -eq 1 ] && [ $manual_dirs -eq 0 ]; then
 		rename_dirs_auto
 		rename_files_manual
-		exit 0
+		return
 	fi
 	# manual renaming both (files + dirs)
 	if [ $manual_files -eq 1 ] && [ $manual_dirs -eq 1 ]; then
@@ -350,16 +350,11 @@ only() {
 	cwd=$(pwd)
 	for dir in "$@"; do
 		# cutting off ending `/` if presented
-		if [[ "$dir" =~ .*\/$ ]]; then
-			dir="${dir%/}"
-		fi
+		[[ "$dir" =~ .*\/$ ]] && dir="${dir%/}"
+
 		if cd "$dir"; then
 			rename_tree
-			if cd "$cwd"; then
-				rename "$dir"
-			else
-				echo "Failed to rename '$dir'"
-			fi
+			cd "$cwd" && rename "$dir" || echo "Failed to rename '$dir'"
 		else
 			echo "Failed to change directory to '$dir'"
 		fi
