rname: all functions (except inner in Rename_Tree() & Exclude()) -> Camel_Plus_Snake_Case refactoring

diff --git a/scripts/rname b/scripts/rname
--- a/scripts/rname
+++ b/scripts/rname
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# rename dir-tree (regular files & directories): lowercase + whitespaces -> '-'
+# Rename dir-tree (regular files & directories): lowercase + whitespaces -> '-'
 # ignoring files and dirs, which begin with `.` | `~`
 # matches existing paths and rename it with new indices
 # as options: exclude || add dirs to rename
@@ -24,7 +24,7 @@ ANTI_SEP="-"
 # functions
 #######################
 
-show_help() {
+Show_Help() {
     cat <<EOF
 
 USAGE:
@@ -93,7 +93,7 @@ EOF
 }
 
 # takes 1 arg: question string
-ask_confirm() {
+Ask_Confirm() {
 	echo "-----------------------"
 	read -rp "$1" answer
 	if [[ "$answer" =~ ^(y|yes|Y|YES)$ ]]; then
@@ -105,7 +105,7 @@ ask_confirm() {
 }
 
 # ask for separator: `_` (1) or `-` (2), Empty - default
-ask_sep() {
+Ask_Sep() {
 	echo "-----------------------"
 	echo "Please, choose the separator, default: {_}:"
 	echo "(1): {_} ('Bla Bla' -> 'bla_bla')"
@@ -122,7 +122,7 @@ ask_sep() {
 	fi
 }
 
-check_no_args() {
+Check_No_Args() {
 	if [ -n "$1" ]; then
 		echo "This command does not take any arguments in this mode."
 		return 1
@@ -131,7 +131,7 @@ check_no_args() {
 }
 
 # check if any arg starts with hyphen
-check_no_more_opts() {
+Check_No_More_Opts() {
 	for i in "$@"; do
 		if [[ "$i" = -n ]] || [[ "$i" = --DRYRUN ]]; then
 			echo "Please, use the --dryrun or -n option only at the beginning of the command."
@@ -145,7 +145,7 @@ check_no_more_opts() {
 	return 0
 }
 
-check_arg_presented() {
+Check_Arg_Presented() {
 	if [ -z "$1" ]; then
 		echo "This command requires one or more arguments in this mode."
 		return 1
@@ -153,7 +153,7 @@ check_arg_presented() {
 	return 0
 }
 
-check_subdir() {
+Check_Subdir() {
 	for d in "$@"; do
 		if [ ! -d "$(pwd)/$d" ]; then
 			echo "Arguments must be subdirectories of the current working directory."
@@ -164,7 +164,7 @@ check_subdir() {
 }
 
 # takes 2 args: object path, object name
-check_extension() {
+Check_Extension() {
 	local path="$1"
 	local name="$2"
 	local regex='^.+\.[a-zA-Z0-9\-\/]+$'
@@ -175,7 +175,7 @@ check_extension() {
 	fi
 }
 
-show_thinking_animation() {
+Show_Thinking_Animation() {
 	local message="Counting items..."
 	local spinner=("⠋" "⠙" "⠹" "⠸" "⠼" "⠴" "⠦" "⠧" "⠇" "⠏")
 	local i=0
@@ -192,7 +192,7 @@ show_thinking_animation() {
 }
 
 # takes 1 arg: old_str; echo new_str
-rename_str() {
+Rename_Str() {
 	local name="$1"
 
 	# Remove all prefixes and suffixes of '-', '_', and ' '
@@ -218,13 +218,12 @@ rename_str() {
 	echo "$name"
 }
 
-# overwriting builtin 'rename' command with a better variant
 # function to rename a file with checking if new name already exists, else renaiming with index
 # handle both arg and stdin
 # performs manual renaming of non-ASCII names if necessary
-rename() {
+Rename() {
 
-	auto_rename() {
+	Auto_Rename() {
 		local path="$1"
 		local prefix="${path%/*}"
 		local name_old="${path##*/}"
@@ -237,11 +236,11 @@ rename() {
 		[ $AUTO_CURRENT -eq $AUTO_TOTAL ] && { printf "\n"; tput cnorm; }
 		fi
 
-		if check_extension "$path" "$name_old"; then
+		if Check_Extension "$path" "$name_old"; then
 			local base_name="${name_old%.*}"
 			local extension="${name_old##*.}"
 
-			base_name_new="$(rename_str "$base_name")"
+			base_name_new="$(Rename_Str "$base_name")"
 			path_new="$prefix/$base_name_new.$extension"
 
 			# check if the new name already exists
@@ -280,7 +279,7 @@ rename() {
 
 		else
 
-			name_new="$(rename_str "$name_old")"
+			name_new="$(Rename_Str "$name_old")"
 			path_new="$prefix/$name_new"
 
 			# check if the new name already exists
@@ -319,7 +318,7 @@ rename() {
 		fi
 	}
 
-	manual_rename() {
+	Manual_Rename() {
 		local path="$1"
 		local prefix="${path%/*}"
 		local name_old="${path##*/}"
@@ -337,7 +336,7 @@ rename() {
 		fi
 		((MANUAL_CURRENT++))
 
-		if check_extension "$path" "$name_old"; then
+		if Check_Extension "$path" "$name_old"; then
 			local base_name="${name_old%.*}"
 			local extension="${name_old##*.}"
 
@@ -418,7 +417,7 @@ rename() {
 	}
 
 	# Function to process a single file path
-	single_path() {
+	Single_Path() {
 		local path="$1"
 		# adding prefix `./` to path when its absent
 		if ! [[ "$path" =~ ^\.\/.* ]]; then
@@ -430,28 +429,28 @@ rename() {
 		if { [ $MANUAL_FILES -eq 1 ] && [ -f "$path" ] && [[ "$name" =~ [^a-zA-Z0-9[:punct:][:space:]] ]]; } || \
 			{ [ $MANUAL_DIRS -eq 1 ] && [ -d "$path" ] && [[ "$name" =~ [^a-zA-Z0-9[:punct:][:space:]] ]]; }; then
 
-			manual_rename "$path"
+			Manual_Rename "$path"
 		else
 
-			auto_rename "$path"
+			Auto_Rename "$path"
 		fi
 	}
 
 	# Check if there are arguments; if yes, iterate over them
 	if [ "$#" -gt 0 ]; then
 		for path in "$@"; do
-			single_path "$path"
+			Single_Path "$path"
 		done
 	else
 		# If no arguments, read from stdin
 		while IFS= read -r path; do
-			single_path "$path"
+			Single_Path "$path"
 		done
 	fi
 }
 
 # sort strings by the number of '/' symbols (replacement for -depth in find command to use in pipeline)
-sort_by_slashes() {
+Sort_By_Slashes() {
 	# Read from stdin
 	while IFS= read -r line; do
 		# Count '/' symbols and print count and line
@@ -461,7 +460,7 @@ sort_by_slashes() {
 }
 
 # filter paths in pipelines by RE conditions in basename
-filter_paths_manual_all() {
+Filter_Paths_Manual_All() {
 	while IFS= read -r path; do
 		local name=""
 		name=$(basename "$path")
@@ -472,7 +471,7 @@ filter_paths_manual_all() {
 }
 
 # filter paths in pipelines by RE conditions in basename
-filter_paths_manual_only() {
+Filter_Paths_Manual_Only() {
 	while IFS= read -r path; do
 		local name=""
 		name=$(basename "$path")
@@ -482,7 +481,7 @@ filter_paths_manual_only() {
 	done
 }
 
-rename_tree() {
+Rename_Tree() {
 
 	# rename all regular files in a tree
 	rename_files_auto() {
@@ -498,7 +497,7 @@ rename_tree() {
 -print0 | xargs -0 -I {} printf '%s\n' '{}' >> "$temp_file"
 
 		while IFS= read -r line; do
-			rename "$line"
+			Rename "$line"
 		done < "$temp_file"
 	}
 
@@ -512,10 +511,10 @@ rename_tree() {
 		find . \
 -type d \( -name '.*' ! -name '.' -o -name '~*' \) -prune \
 -o -type d \( -name '* *' -o -name '*[[:upper:]]*' -o -name "*$ANTI_SEP*" \) \
--print0 | xargs -0 -I {} printf '%s\n' '{}' | sort_by_slashes >> "$temp_file"
+-print0 | xargs -0 -I {} printf '%s\n' '{}' | Sort_By_Slashes >> "$temp_file"
 
 		while IFS= read -r line; do
-			rename "$line"
+			Rename "$line"
 		done < "$temp_file"
 	}
 
@@ -529,10 +528,10 @@ rename_tree() {
 -type d \( -name '.*' ! -name '.' -o -name '~*' \) -prune \
 -o -type f ! \( -name '.*' -o -name '~*' \) \
 -print0 | xargs -0 -I {} printf '%s\n' '{}' | \
-filter_paths_manual_all >> "$temp_file"
+Filter_Paths_Manual_All >> "$temp_file"
 
 		while IFS= read -r line; do
-			rename "$line"
+			Rename "$line"
 		done < "$temp_file"
 	}
 
@@ -546,10 +545,10 @@ filter_paths_manual_all >> "$temp_file"
 -type d \( -name '.*' ! -name '.' -o -name '~*' \) -prune \
 -o -type d \
 -print0 | xargs -0 -I {} printf '%s\n' '{}' | \
-filter_paths_manual_all | sort_by_slashes >> "$temp_file"
+Filter_Paths_Manual_All | Sort_By_Slashes >> "$temp_file"
 
 		while IFS= read -r line; do
-			rename "$line"
+			Rename "$line"
 		done < "$temp_file"
 	}
 
@@ -573,7 +572,7 @@ filter_paths_manual_all | sort_by_slashes >> "$temp_file"
 -type d \( -name '.*' ! -name '.' -o -name '~*' \) -prune \
 -o -type f ! \( -name '.*' -o -name '~*' \) \
 -print0 | xargs -0 -I {} printf '%s\n' '{}' | \
-filter_paths_manual_only | wc -l
+Filter_Paths_Manual_Only | wc -l
 	}
 
 	count_dirs_manual() {
@@ -581,7 +580,7 @@ filter_paths_manual_only | wc -l
 -type d \( -name '.*' ! -name '.' -o -name '~*' \) -prune \
 -o -type d \
 -print0 | xargs -0 -I {} printf '%s\n' '{}' | \
-filter_paths_manual_only | wc -l
+Filter_Paths_Manual_Only | wc -l
 	}
 
 	# no manual
@@ -590,7 +589,7 @@ filter_paths_manual_only | wc -l
 		echo "-----------------------"
 		echo "Renaming tree: '$(pwd)'"
 
-		show_thinking_animation &
+		Show_Thinking_Animation &
 		animation_pid=$!
 		AUTO_TOTAL=$(( $(count_files_auto) + $(count_dirs_auto) ))
 		kill $animation_pid 2>/dev/null
@@ -625,7 +624,7 @@ filter_paths_manual_only | wc -l
 	fi
 }
 
-only() {
+Only() {
 
 	check_dir_name() {
 		local dir="$1"
@@ -646,10 +645,10 @@ only() {
 		[[ "$dir" =~ .*\/$ ]] && dir="${dir%/}"
 
 		if cd "$dir"; then
-			rename_tree
+			Rename_Tree
 			cd "$cwd" || { echo "Failed to change directory to '$cwd'"; exit 1; }
 			if check_dir_name "$dir"; then
-				rename "$dir" || echo "Failed to rename '$dir'"
+				Rename "$dir" || echo "Failed to rename '$dir'"
 			fi
 		else
 			echo "Failed to change directory to '$dir'"
@@ -657,7 +656,7 @@ only() {
 	done
 }
 
-exclude() {
+Exclude() {
 	local exclude_dirs_find=""
 	local exclude_dirs_massage=""
 	for pattern in "$@"; do
@@ -680,7 +679,7 @@ exclude() {
 -o -type f ! \( -name '.*' -o -name '~*' \) \
 -a \( -name '* *' -o -name '*[[:upper:]]*' -o -name '*$ANTI_SEP*' \) \
 -print0 | xargs -0 -I {} printf '%s\n' '{}'"
-		eval "$str_files" | rename
+		eval "$str_files" | Rename
 	}
 
 	rename_dirs_auto() {
@@ -689,7 +688,7 @@ exclude() {
 -type d \( -name '.*' ! -name '.' -o -name '~*' $exclude_dirs_find\) -prune \
 -o -type d \( -name '* *' -o -name '*[[:upper:]]*' -o -name '*$ANTI_SEP*' \) \
 -print0 | xargs -0 -I {} printf '%s\n' '{}'"
-		eval "$str_dirs" | sort_by_slashes | rename
+		eval "$str_dirs" | Sort_By_Slashes | Rename
 	}
 
 	rename_files_manual() {
@@ -703,10 +702,10 @@ exclude() {
 -type d \( -name '.*' ! -name '.' -o -name '~*' $exclude_dirs_find\) -prune \
 -o -type f ! \( -name '.*' -o -name '~*' \) \
 -print0 | xargs -0 -I {} printf '%s\n' '{}'"
-		eval "$str_files" | filter_paths_manual_all  >> "$temp_file"
+		eval "$str_files" | Filter_Paths_Manual_All  >> "$temp_file"
 
 		while IFS= read -r line; do
-			rename "$line"
+			Rename "$line"
 		done < "$temp_file"
 	}
 
@@ -721,10 +720,10 @@ exclude() {
 -type d \( -name '.*' ! -name '.' -o -name '~*' $exclude_dirs_find\) -prune \
 -o -type d \
 -print0 | xargs -0 -I {} printf '%s\n' '{}'"
-		eval "$str_dirs" | filter_paths_manual_all | sort_by_slashes >> "$temp_file"
+		eval "$str_dirs" | Filter_Paths_Manual_All | Sort_By_Slashes >> "$temp_file"
 
 		while IFS= read -r line; do
-			rename "$line"
+			Rename "$line"
 		done < "$temp_file"
 	}
 
@@ -754,7 +753,7 @@ exclude() {
 -o -type f ! \( -name '.*' -o -name '~*' \) \
 -a \( -name '*[! -~]*' \) \
 -print"
-		eval "$str_files" | filter_paths_manual_only | wc -l
+		eval "$str_files" | Filter_Paths_Manual_Only | wc -l
 	}
 
 	count_dirs_manual() {
@@ -763,7 +762,7 @@ exclude() {
 -type d \( -name '.*' ! -name '.' -o -name '~*' $exclude_dirs_find \) -prune \
 -o -type d \( -name '*[! -~]*' \) \
 -print"
-		eval "$str_dirs" | filter_paths_manual_only | wc -l
+		eval "$str_dirs" | Filter_Paths_Manual_Only | wc -l
 	}
 
 	# no manual
@@ -772,7 +771,7 @@ exclude() {
 		echo "-----------------------"
 		echo "Renaming tree: '$(pwd)' excluding dirs: $exclude_dirs_massage"
 
-		show_thinking_animation &
+		Show_Thinking_Animation &
 		animation_pid=$!
 		AUTO_TOTAL=$(( $(count_files_auto) + $(count_dirs_auto) ))
 		kill $animation_pid 2>/dev/null
@@ -892,161 +891,161 @@ esac
 
 # no args
 if [ $OPTION -eq 0 ]; then
-	check_no_more_opts "$@" || exit 1
-	check_no_args "$@" || exit 1
-	ask_confirm "Are you sure you want to rename the entire directory tree under '$(pwd)'? (y/n): " || exit 1
-	ask_sep || exit 1
+	Check_No_More_Opts "$@" || exit 1
+	Check_No_Args "$@" || exit 1
+	Ask_Confirm "Are you sure you want to rename the entire directory tree under '$(pwd)'? (y/n): " || exit 1
+	Ask_Sep || exit 1
 
-	rename_tree
+	Rename_Tree
 
 	exit 0
 fi
 
 # only
 if [ $OPTION -eq 2 ]; then
-	check_no_more_opts "$@" || exit 1
-	check_arg_presented "$@" || exit 1
-	check_subdir "$@" || exit 1
-	ask_confirm "Are you sure you want to rename all directory trees in the selected folders, including their names? (y/n): " || exit 1
-	ask_sep || exit 1
+	Check_No_More_Opts "$@" || exit 1
+	Check_Arg_Presented "$@" || exit 1
+	Check_Subdir "$@" || exit 1
+	Ask_Confirm "Are you sure you want to rename all directory trees in the selected folders, including their names? (y/n): " || exit 1
+	Ask_Sep || exit 1
 
-	only "$@"
+	Only "$@"
 	
 	exit 0
 fi
 
 # exclude
 if [ $OPTION -eq 1 ]; then
-	check_no_more_opts "$@" || exit 1
-	check_arg_presented "$@" || exit 1
-	check_subdir "$@" || exit 1
-	ask_confirm "Are you sure you want to rename the entire directory tree under '$(pwd)', excluding the selected folders and their contents? (y/n): " || exit 1
-	ask_sep || exit 1
+	Check_No_More_Opts "$@" || exit 1
+	Check_Arg_Presented "$@" || exit 1
+	Check_Subdir "$@" || exit 1
+	Ask_Confirm "Are you sure you want to rename the entire directory tree under '$(pwd)', excluding the selected folders and their contents? (y/n): " || exit 1
+	Ask_Sep || exit 1
 
-	exclude "$@"
+	Exclude "$@"
 	
 	exit 0
 fi
 
 # files
 if [ $OPTION -eq 3 ]; then
-	check_no_more_opts "$@" || exit 1
-	check_no_args "$@" || exit 1
-	ask_confirm "Are you sure you want to rename the entire directory tree under '$(pwd)', with manual renaming required for each non-ASCII filename? (y/n): " || exit 1
-	ask_sep || exit 1
+	Check_No_More_Opts "$@" || exit 1
+	Check_No_Args "$@" || exit 1
+	Ask_Confirm "Are you sure you want to rename the entire directory tree under '$(pwd)', with manual renaming required for each non-ASCII filename? (y/n): " || exit 1
+	Ask_Sep || exit 1
 
-	rename_tree
+	Rename_Tree
 	
 	exit 0
 fi
 
 # only + files
 if [ $OPTION -eq 32 ]; then
-	check_no_more_opts "$@" || exit 1
-	check_arg_presented "$@" || exit 1
-	check_subdir "$@" || exit 1
-	ask_confirm "Are you sure you want to rename all directory trees in the selected folders (including their names), with manual renaming required for each regular file containing non-ASCII characters? (y/n): " || exit 1
-	ask_sep || exit 1
+	Check_No_More_Opts "$@" || exit 1
+	Check_Arg_Presented "$@" || exit 1
+	Check_Subdir "$@" || exit 1
+	Ask_Confirm "Are you sure you want to rename all directory trees in the selected folders (including their names), with manual renaming required for each regular file containing non-ASCII characters? (y/n): " || exit 1
+	Ask_Sep || exit 1
 
-	only "$@"
+	Only "$@"
 	
 	exit 0
 fi
 
 # exclude + files
 if [ $OPTION -eq 31 ]; then
-	check_no_more_opts "$@" || exit 1
-	check_arg_presented "$@" || exit 1
-	check_subdir "$@" || exit 1
-	ask_confirm "Are you sure you want to rename the entire directory tree under '$(pwd)' (excluding selected folders and their contents), with manual renaming required for each regular file containing non-ASCII characters? (y/n): " || exit 1
-	ask_sep || exit 1
+	Check_No_More_Opts "$@" || exit 1
+	Check_Arg_Presented "$@" || exit 1
+	Check_Subdir "$@" || exit 1
+	Ask_Confirm "Are you sure you want to rename the entire directory tree under '$(pwd)' (excluding selected folders and their contents), with manual renaming required for each regular file containing non-ASCII characters? (y/n): " || exit 1
+	Ask_Sep || exit 1
 
-	exclude "$@"
+	Exclude "$@"
 	
 	exit 0
 fi
 
 # dirs
 if [ $OPTION -eq 4 ]; then
-	check_no_more_opts "$@" || exit 1
-	check_no_args "$@" || exit 1
-	ask_confirm "Are you sure you want to rename the entire directory tree under '$(pwd)', with manual renaming required for each directory containing non-ASCII characters in its name? (y/n): " || exit 1
-	ask_sep || exit 1
+	Check_No_More_Opts "$@" || exit 1
+	Check_No_Args "$@" || exit 1
+	Ask_Confirm "Are you sure you want to rename the entire directory tree under '$(pwd)', with manual renaming required for each directory containing non-ASCII characters in its name? (y/n): " || exit 1
+	Ask_Sep || exit 1
 
-	rename_tree
+	Rename_Tree
 	
 	exit 0
 fi
 
 # only + dirs
 if [ $OPTION -eq 42 ]; then
-	check_no_more_opts "$@" || exit 1
-	check_arg_presented "$@" || exit 1
-	check_subdir "$@" || exit 1
-	ask_confirm "Are you sure you want to rename all directory trees in the selected folders (including their names), with manual renaming required for each directory containing non-ASCII characters in its name? (y/n): " || exit 1
-	ask_sep || exit 1
+	Check_No_More_Opts "$@" || exit 1
+	Check_Arg_Presented "$@" || exit 1
+	Check_Subdir "$@" || exit 1
+	Ask_Confirm "Are you sure you want to rename all directory trees in the selected folders (including their names), with manual renaming required for each directory containing non-ASCII characters in its name? (y/n): " || exit 1
+	Ask_Sep || exit 1
 
-	only "$@"
+	Only "$@"
 	
 	exit 0
 fi
 
 # exclude + dirs
 if [ $OPTION -eq 41 ]; then
-	check_no_more_opts "$@" || exit 1
-	check_arg_presented "$@" || exit 1
-	check_subdir "$@" || exit 1
-	ask_confirm "Are you sure you want to rename the entire directory tree under '$(pwd)' (excluding selected folders and their contents), with manual renaming required for each directory containing non-ASCII characters in its name? (y/n): " || exit 1
-	ask_sep || exit 1
+	Check_No_More_Opts "$@" || exit 1
+	Check_Arg_Presented "$@" || exit 1
+	Check_Subdir "$@" || exit 1
+	Ask_Confirm "Are you sure you want to rename the entire directory tree under '$(pwd)' (excluding selected folders and their contents), with manual renaming required for each directory containing non-ASCII characters in its name? (y/n): " || exit 1
+	Ask_Sep || exit 1
 
-	exclude "$@"
+	Exclude "$@"
 	
 	exit 0
 fi
 
 # both
 if [ $OPTION -eq 5 ]; then
-	check_no_more_opts "$@" || exit 1
-	check_no_args "$@" || exit 1
-	ask_confirm "Are you sure you want to rename the entire directory tree under '$(pwd)', with manual renaming required for each directory and regular file containing non-ASCII characters in their names? (y/n): " || exit 1
-	ask_sep || exit 1
+	Check_No_More_Opts "$@" || exit 1
+	Check_No_Args "$@" || exit 1
+	Ask_Confirm "Are you sure you want to rename the entire directory tree under '$(pwd)', with manual renaming required for each directory and regular file containing non-ASCII characters in their names? (y/n): " || exit 1
+	Ask_Sep || exit 1
 
-	rename_tree
+	Rename_Tree
 	
 	exit 0
 fi
 
 # only + both
 if [ $OPTION -eq 52 ]; then
-	check_no_more_opts "$@" || exit 1
-	check_arg_presented "$@" || exit 1
-	check_subdir "$@" || exit 1
-	ask_confirm "Are you sure you want to rename all directory trees in the selected folders (including their names), with manual renaming required for each directory and file containing non-ASCII characters in their names? (y/n): " || exit 1
-	ask_sep || exit 1
+	Check_No_More_Opts "$@" || exit 1
+	Check_Arg_Presented "$@" || exit 1
+	Check_Subdir "$@" || exit 1
+	Ask_Confirm "Are you sure you want to rename all directory trees in the selected folders (including their names), with manual renaming required for each directory and file containing non-ASCII characters in their names? (y/n): " || exit 1
+	Ask_Sep || exit 1
 
-	only "$@"
+	Only "$@"
 	
 	exit 0
 fi
 
 # exclude + both
 if [ $OPTION -eq 51 ]; then
-	check_no_more_opts "$@" || exit 1
-	check_arg_presented "$@" || exit 1
-	check_subdir "$@" || exit 1
-	ask_confirm "Are you sure you want to rename the entire directory tree under '$(pwd)' (excluding selected folders and their contents), with manual renaming required for each directory and file containing non-ASCII characters in their names? (y/n): " || exit 1
-	ask_sep || exit 1
+	Check_No_More_Opts "$@" || exit 1
+	Check_Arg_Presented "$@" || exit 1
+	Check_Subdir "$@" || exit 1
+	Ask_Confirm "Are you sure you want to rename the entire directory tree under '$(pwd)' (excluding selected folders and their contents), with manual renaming required for each directory and file containing non-ASCII characters in their names? (y/n): " || exit 1
+	Ask_Sep || exit 1
 
-	exclude "$@"
+	Exclude "$@"
 	
 	exit 0
 fi
 
 # help
 if [ $OPTION -eq 6 ]; then
-	check_no_more_opts "$@" || exit 1
-	check_no_args "$@" || exit 1
-	show_help
+	Check_No_More_Opts "$@" || exit 1
+	Check_No_Args "$@" || exit 1
+	Show_Help
 
 	# TODO: action
 fi
