videocut: fix_time_format() added

diff --git a/scripts/videocut/videocut b/scripts/videocut/videocut
--- a/scripts/videocut/videocut
+++ b/scripts/videocut/videocut
@@ -34,6 +34,27 @@ run_ffmpeg() {
 	fi
 }
 
+fix_time_format() {
+	local time_str=$1
+
+	# check 00:00:00:00
+	if [[ $time_str =~ ^([0-9]{2}:){3}[0-9]{2}$ ]]; then
+		echo "${time_str%:*}.${time_str##*:}"
+
+	# check 00:00:00.00
+	elif [[ $time_str =~ ^([0-9]{2}:){2}[0-9]{2}\.[0-9]{2}$ ]]; then
+		echo "$time_str"
+
+	# check [None, none, False, false]
+	elif [[ "$time_str" == "None" || "$time_str" == "none" || "$time_str" == "False" || "$time_str" == "false" ]]; then
+		echo "$time_str"
+
+	else
+		echo "Error: incorrect time format '$time_str' in timecodes file." >&2
+		return 1
+	fi
+}
+
 # ========================================================
 # SCRIPT
 # ========================================================
@@ -101,7 +122,9 @@ tac "$time_codes" | while read -r line; do
 
 	# get data from line
 	start_time=$(echo "$line" | awk '{print $1}')
+	start_time=$(fix_time_format "$start_time")
 	end_time=$(echo "$line" | awk '{print $2}')
+	end_time=$(fix_time_format "$end_time")
 
 	if [[ "$start_time" == "None" || "$start_time" == "none" || "$start_time" == "False" || "$start_time" == "false" ]]; then
 		run_ffmpeg -i "$output_video_file" -ss "$end_time" -c copy temp_file.mp4
